name: go-main
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: {{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: go test -coverprofile c.out ./...
        coverageLocations: ${{github.workspace}}/c.out:gocov
